# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  example:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      # home path
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric

      # =================================================================================================================
      # ============= ENV variables for configuration (can be instead by '%FABRIC_CFG_PATH%/orderer.yaml') ==============
      # general settings
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      # TLS settings
      - ORDERER_GENERAL_TLS_ENABLED=|TLS_ENABLED|
      - ORDERER_GENERAL_TLS_PRIVATEKEY=tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[tls/ca.crt]
      #genesis settings
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=msp
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      # =================================================================================================================

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      # =================================================================================================================
      # ============= YAML files for configuration to override default in '%FABRIC_CFG_PATH%/orderer.yaml' ==============
      # - ./config/orderer.example.com.yaml:/etc/hyperledger/fabric/orderer.yaml
      # =================================================================================================================

      - ./channel-artifacts/genesis.block:/etc/hyperledger/fabric/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/etc/hyperledger/fabric/tls
    ports:
      - 7050:7050
    networks:
      - example

  ca.org1.example.com:
    container_name: ca.org1.example.com
    image: hyperledger/fabric-ca:$CA_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server

      # ===================================================================================================================================
      # =============== ENV Variables for configuration (can be instead by '%FABRIC_CA_HOME%/fabric-ca-server-config.yaml') ===============
      # CA settings
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_CERTFILE=msp/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_KEYFILE=msp/|CA1_PRIVATE_KEY|
      - FABRIC_CA_SERVER_TLS_ENABLED=|TLS_ENABLED|
      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/|CA1_PRIVATE_KEY|
      # ===================================================================================================================================

    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      # ================================================================================================================================
      # =============== YAML file for configuration to override default in '%FABRIC_CFG_PATH%/core.yaml' ===============================
      # - ./config/ca.org1.example.com.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      # ================================================================================================================================

      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server/msp
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server/tls
    networks:
      - example

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      # home path
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric

      # =================================================================================================================
      # =============== ENV Variables for configuration (can be instead by '%FABRIC_CFG_PATH%/core.yaml') ===============
      # peer settings
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_NETWORKID=example-network
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_MSPCONFIGPATH=msp
      - CORE_PEER_LOCALMSPID=Org1MSP
      # tls settings
      - CORE_PEER_TLS_ENABLED=|TLS_ENABLED|
      - CORE_PEER_TLS_CERT_FILE=tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=tls/ca.crt
      # vm settings
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_$NETWORK_NAME
      # chaincode settings
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:$IMAGE_TAG
      - CORE_CHAINCODE_PULL=false
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:$BASE_TAG
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:$IMAGE_TAG
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:$IMAGE_TAG
      - CORE_CHAINCODE_MODE=net
      - CORE_CHAINCODE_LOGGIN_LEVEL=info
      - CORE_CHAINCODE_LOGGIN_SHIM=warning
      # couchdb_settings
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB #(goleveldb | CouchDB, default=goleveldb)
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=db.peer0.org1.example.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      # history_db_enabled
      - CORE_HISTORY_ENABLEHISTORYDATABASE=true
      # =================================================================================================================

    volumes:
      # =================================================================================================================
      # =============== YAML file for configuration to override default in '%FABRIC_CFG_PATH%/core.yaml' ================
      # - ./config/peer0.org1.example.com.yaml:/etc/hyperledger/fabric/core.yaml
      # =================================================================================================================
      - /var/run/:/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      # - peer0.org1.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - example

  db.peer0.org1.example.com:
    container_name: db.peer0.org1.example.com
    image: hyperledger/fabric-couchdb:$BASE_TAG
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - example

  ca.org2.example.com:
    container_name: ca.org2.example.com
    image: hyperledger/fabric-ca:$CA_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server

      # ===================================================================================================================================
      # =============== ENV Variables for configuration (can be instead by '%FABRIC_CA_HOME%/fabric-ca-server-config.yaml') ===============
      # CA settings
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_CERTFILE=msp/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_KEYFILE=msp/|CA2_PRIVATE_KEY|
      # TLS settings
      - FABRIC_CA_SERVER_TLS_ENABLED=|TLS_ENABLED|
      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/|CA2_PRIVATE_KEY|
      # ===================================================================================================================================

    ports:
      - "6054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      # ================================================================================================================================
      # =============== YAML file for configuration to override default in '%FABRIC_CFG_PATH%/core.yaml' ===============================
      # - ./config/ca.org2.example.com.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      # ================================================================================================================================
      
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server/msp
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server/tls
    networks:
      - example

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      # home path
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric

      # =================================================================================================================
      # =============== ENV Variables for configuration (can be instead by '%FABRIC_CFG_PATH%/core.yaml') ===============
      # peer settings
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_NETWORKID=example-network
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_PEER_MSPCONFIGPATH=msp
      - CORE_PEER_LOCALMSPID=Org2MSP
      # tls settings
      - CORE_PEER_TLS_ENABLED=|TLS_ENABLED|
      - CORE_PEER_TLS_CERT_FILE=tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=tls/ca.crt
      # vm settings
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_$NETWORK_NAME
      # chaincode settings
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:$IMAGE_TAG
      - CORE_CHAINCODE_PULL=false
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:$BASE_TAG
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:$IMAGE_TAG
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:$IMAGE_TAG
      - CORE_CHAINCODE_MODE=net
      - CORE_CHAINCODE_LOGGIN_LEVEL=info
      - CORE_CHAINCODE_LOGGIN_SHIM=warning
      # couchdb_settings
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB #(goleveldb | CouchDB, default=goleveldb)
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=db.peer0.org1.example.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      # history_db_enabled
      - CORE_HISTORY_ENABLEHISTORYDATABASE=true
      # =================================================================================================================

    volumes:
      # =================================================================================================================
      # =============== YAML file for configuration to override default in '%FABRIC_CFG_PATH%/core.yaml' ================
      # - ./config/peer0.org2.example.com.yaml:/etc/hyperledger/fabric/core.yaml
      # =================================================================================================================

      - /var/run/:/var/run/
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
      # - peer0.org1.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 6051:7051
      - 6053:7053
    networks:
      - example

  db.peer0.org2.example.com:
    container_name: db.peer0.org2.example.com
    image: hyperledger/fabric-couchdb:$BASE_TAG
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 4984:5984
    networks:
      - example

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=|TLS_ENABLED|
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/var/run/
      - ./../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
    networks:
      - example
